server:
  port: 5051
  tomcat:
    max-connections: 10
    max-http-form-post-size: 4MB
    max-swallow-size: 4MB
    accesslog:
      max-days: 10
spring:
  application:
    name: cyber-done-account-microservice
  profiles:
    active: prod
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account-micro
  flyway:
    user: root
    password: root
    encoding: utf-8
    url: jdbc:mysql://localhost:3306/account-micro
  jpa:
    hibernate:
      ddl-auto: validate

cache:
  token:
    time-to-live-seconds: 600
    eviction-policy: LRU
    max-entries-in-heap: 100
  account:
    time-to-live-seconds: 600
    eviction-policy: LRU
    max-entries-in-heap: 100
  permission:
    time-to-live-seconds: 600
    eviction-policy: LRU
    max-entries-in-heap: 100

security:
  jwt-secret: d2980f58-3d82-4144-b802-406f4b47930b-5784cca4-0b50-425e-ac6c-bd651e0c788d
  jwt-expiration-time-ms: 86400000 #24 hours 86400000
---
spring:
  config:
    activate:
      on-profile: prod
security:
  jwt-secret: d2980f58-3d82-4144-b802-406f4b47930b-5784cca4-0b50-425e-ac6c-bd651e0c788d
  jwt-expiration-time-ms: 86400000 #24 hours